apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dockerexample-rs
  labels:
    app: dockerexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerexample
  template:
    metadata:
      name: dockerexample
      labels:
        app: dockerexample
    spec:
      containers:
        - name: dockerexample
          image: nam908/docker-demo
          imagePullPolicy: IfNotPresent
      restartPolicy: Always